04-vue-cli: Готово
js-tasks-ru/vue-20230320_aleksey-titekin pull request #5
Opened 2023-04-05 14:52 UTC by AlekseyTitekin

Прошу уделить больше внимания задаче 02-TheToaster. Решена двумя способами, через массив (isArray = true) и через Map (isArray = false). Визуально решения оба корректны, но решение через Map не проходит тест на последовательность.

2023-04-05 14:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-05 19:14 UTC, ShGKme requested changes
В `04-vue-cli/02-TheToaster` нельзя использовать `Date.now()` в качестве идентификатора.

В `04-vue-cli/04-MeetupsCalendar` лучше решить задачу без переболра всех данных внутри цикла в шаблоне компонента.

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
>      <!-- form-group_inline -->
Оборачивание в массив здесь лишнее

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      const id = Date.now();
`Date.now()` нельзя использовать в качестве идентификатора. Не гарантируется его уникальность. Два подряд вызова функции могут быть быстрее, чем за 0.001с

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      const id = Date.now();
Именно это могло быть причиной проблемы решения с Map. Порядок элементов в Map соответствует вставке, решение с Map должно работать.

В целом тут даже быстрее работает на массиве, потому что обычно тостов одновременно очень мало. Обычно это 2-3 тоста.

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  <div :class="{'toast toast_success': isSuccess, 'toast toast_error': isError}">
Статичный класс вёрстки можно оставить отдельным атрибутом, чтобы не добавлять его везде, и явно видеть какие классы - статичные классы вёрстки, а какие - динамические.

```html
<div class="toast" :class="{ toast_success: isSuccess, toast_error: isError }">
```

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
За один проход можно проверить методом some: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  },
Начальным значением месяца указана функция-конструктор...

2023-04-05 19:14 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
>        </div>
Сейчас во время рендеринга вызывается метод. Вызывать метод в шаблоне в целом обычно не лучшая практика. Это делает шаблон не декларативным, и требует дополнительно проверять, что метод не имеет побочных эффектов и производительный. Иногда это допустимо, когда метод используется для форматирования вывода или немного упрощает код в компоненте.

Но метод `currentDayMeetups` здесь используется для описания логики работы с данными - формирует массив данных для дочернего компонента прямо во время рендеринга. Это уже перетекание логики обработки данных в шаблон, при этом неоптимальное.

В итоге сейчас при рендеринге КАЖДОЙ ячейки календаря происходит перебор всех-всех митапов (включая те, которые вообще не относятся к этому месяцу или уже выводились в другой ячейки) для проверки, а не попадает ли этот митап в эту ячейку. Потом ещё раз для следующей ячейки. И так для всех дней месяца. И всё это повторяется при каждом ререндеринге компонента, даже если результат не изменится.

Вместо этого лучше готовить данные для их удобного вывода без дополнительных перевычислений.

2023-04-06 08:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-06 11:03 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-04-06 11:03 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
>        }
Лучше, так как теперь митапы не вычисляются прямо во время рендеринга в шаблоне, но в остальном это также не очень оптимальное решение с полным перебором всех митапов для каждой ячейки.

2023-04-06 11:04 UTC, merged