07-forms: Готово
js-tasks-ru/vue-20230320_aleksey-titekin pull request #8
Opened 2023-04-16 16:30 UTC by AlekseyTitekin

2023-04-16 16:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-16 16:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-17 07:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-04-17 22:29 UTC, ShGKme requested changes
Требуется небольшое исправление в `07-forms/04-GeneratedForm`, остальные задачи приняты

2023-04-17 22:29 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
`fieldForTypeItems` не используется в шаблоне, его можно не добавлять в `options`, работая с ним напрямую, как с обычной константой.

2023-04-17 22:29 UTC, ShGKme commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
>      </UiFormGroup>
Здесь устанавливаются все возможные параметры для всех возможных компонентов. В таком решении с одной стороны, в компоненты привязываются параметры, которых у них нет, с другой, при изменении схемы, добавлении новых компонентов с новыми параметрами, нужно добавлять их и сюда. 

Вместо этого требуется привязать ровно все параметры из `item.props`.

2023-04-18 10:23 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-18 13:37 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-04-18 13:38 UTC, merged